### ISSUE TITLE
User - model mapping

### ISSUE THREAD

**Issue by wstobinski** [wstobinski/zzpj#36]
### Map user objects to their model references
User class needs a new property: modelReferenceId referencing an instance of Referee/Player depending on user role.
It is needed to prevent unauthorized users from accessing forbidden data (data not associated with them).

Depending on user's role, Referee or Player object will be retrieved from database.

**Comment by Nutritious-prog** [comment]
![image](https://github.com/wstobinski/zzpj/assets/78347205/1a2b1a08-e89b-4040-8ce1-6bba9a854fb0)
